---
- hosts: all
  tasks:

  - apt: upgrade=dist update_cache=yes force=yes dpkg_options="force-confdef,force-confold"
    environment:
      DEBIAN_FRONTEND: noninteractive
    sudo: yes

  #  # dpkg -L linux-image*
  # - name: Remove old kernels
  #   apt: name={{ item }} purge=yes state=absent
  #   with_items:
  #     - linux-image-3.13.0-62-generic
  #     - linux-image-extra-3.13.0-62-generic

  - name: Install workstation apps
    apt: name={{ item }} state=latest
    sudo: yes
    with_items:
      - indicator-multiload
      - curl
      - alien    # To install rpms
      - libaio1  # sqlplus client requires them
      - compizconfig-settings-manager # Optimisations to remove fancy UI
      - unity-tweak-tool
      - htop
      - git
      - yakuake
      - sqlite3
      - vim
      - wget
      - aria2
      - aptitude

  # - name: download java 8
  #   shell: aria2c -x 16 -s 16 --check-certificate=false --header 'Cookie:oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.tar.gz --dir /install-bucket/linux/java
  # - name: download java 7
  #   shell: aria2c -x 16 -s 16 --check-certificate=false --header 'Cookie:oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz --dir /install-bucket/linux/java
  # - name: download java 6
  #   shell: aria2c -x 16 -s 16 --check-certificate=false --header 'Cookie:oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn/java/jdk/6u45-b06/jdk-6u45-linux-x64.bin --dir /install-bucket/linux/java

  - shell: curl -L -s get.jenv.io | bash
  - shell: curl -s http://get.sdkman.io | bash
  - shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.26.1/install.sh | bash
  # - name: install java 6
  #   shell: sudo -iu vagrant jenv install java 1.6.0_45
  - file: path=/usr/lib/jvm state=directory
    sudo: yes
  - unarchive: src=~/Downloads/linux/java/jdk-8u60-linux-x64.tar.gz dest=/usr/lib/jvm
    sudo: yes
  - unarchive: src=~/Downloads/linux/java/jdk-7u79-linux-x64.tar.gz dest=/usr/lib/jvm
    sudo: yes
  - file: path=/home/vagrant/.jenv/candidates/java state=directory
  - file: path=/home/vagrant/.jenv/candidates/java/1.7.0_79 src=/usr/lib/jvm/jdk1.7.0_79 state=link
  - file: path=/home/vagrant/.jenv/candidates/java/1.8.0_60 src=/usr/lib/jvm/jdk1.8.0_60 state=link
  - unarchive: src=~/Downloads/linux/intellij/ideaIC-14.1.4.tar.gz dest=~
  - unarchive: src=~/Downloads/linux/eclipse/spring-tool-suite-3.7.0.RELEASE-e4.5-linux-gtk-x86_64.tar.gz dest=~


  #   # SQL Developer
  - file: path=/usr/local/lib/oracle state=directory
    sudo: yes
  - unarchive: src=~/Downloads/linux/oracle/sqldeveloper-4.1.1.19.59-no-jre.zip dest=/usr/local/lib/oracle
    sudo: yes
  - file: src=/usr/local/lib/oracle/sqldeveloper/sqldeveloper.sh path=/usr/local/bin/sqldeveloper state=link
    sudo: yes
  # - copy: src=usr/share/applications/sqldeveloper.desktop dest=/usr/share/applications/sqldeveloper.desktop
  #   notify: update-desktop-database

  #   # Freemind
  # - unarchive: src=/install-bucket/{{ freemind }}.zip dest=/opt/dev/java/freemind creates=/opt/dev/java/freemind/freemind.sh owner=vagrant group=vagrant
  # - copy: src=/install-bucket/Free_Mind.png dest=/opt/dev/java/freemind/Free_Mind.png
  # - file: dest=/opt/dev/java/freemind/freemind.sh mode=755
  # - file: src=/opt/dev/java/freemind/freemind.sh path=/usr/local/bin/freemind state=link
  # - copy: src=usr/share/applications/freemind.desktop dest=/usr/share/applications/freemind.desktop
  #   notify: update-desktop-database

  #   # SQL*Plus
  - command: alien -i /install-bucket/linux/oracle/oracle-instantclient12.1-basiclite-12.1.0.2.0-1.x86_64.rpm
    sudo: yes
  #   args:
  #     creates: /usr/lib/oracle
  - command: alien -i /install-bucket/linux/oracle/oracle-instantclient12.1-sqlplus-12.1.0.2.0-1.x86_64.rpm
    sudo: yes
  #   args:
  #     creates: /usr/bin/sqlplus64
  # - file: src=/usr/bin/sqlplus64 path=/usr/bin/sqlplus state=link
  #   # export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib/:$LD_LIBRARY_PATH
  #   # export ORACLE_SID=XE

  #   # FIXME Remove this fix "--touch-devices=123" when this issue is closed https://code.google.com/p/chromium/issues/detail?id=465660
  # - copy: src=usr/share/applications/google-chrome.desktop dest=/usr/share/applications/

  #   # Set the proxy in git
  # - command: git config --global http.proxy {{ lookup('env', 'http_proxy') }}
  #   sudo: no
  #   changed_when: false # Should really detect a change but this will do for now
  # - command: git config --global https.proxy {{ lookup('env', 'https_proxy') }}
  #   sudo: no
  #   changed_when: false # Should really detect a change but this will do for now

  #   # Global git ignore
  # - copy: src=home/vagrant/gitignore_global dest=/home/vagrant/.gitignore_global
  # - command: git config --global core.excludesfile /home/vagrant/.gitignore_global
  #   sudo: no
  #   changed_when: false # Should really detect a change but this will do for now

  #   # Install hipchat (Disabled, looked like it was not working because of proxy)
  # - apt_key: id=729B5780 url=https://www.hipchat.com/keys/hipchat-linux.key state=absent
  # - apt_repository: repo='deb http://downloads.hipchat.com/linux/apt stable main' update_cache=yes state=absent
  # - apt: package=hipchat state=absent

  #   # Setup the user mount
  # - mount: name=/home/vagrant/Documents src=//aur.national.com.au/User_Data/AU-VIC-Melbourne-3COL3-01/UserData/P732238 fstype=cifs opts=rw,credentials=/home/vagrant/.smbpasswd,noexec,uid=vagrant,gid=vagrant state=mounted

  #   # Scala
  # - unarchive: src=/install-bucket/{{ scala }}.tgz dest=/opt/dev/scala creates=/opt/dev/scala/{{ scala }} owner=vagrant group=vagrant
  # - file: src=/opt/dev/scala/{{ scala }}/bin/scala path=/usr/local/bin/scala state=link

  #   # sbt
  # - apt_repository: repo='deb http://dl.bintray.com/sbt/debian /' update_cache=yes state=absent
  # - apt: package=sbt state=absent
  # - unarchive: src=/install-bucket/{{ sbt }}.tgz dest=/opt/dev/scala creates=/opt/dev/scala/{{ sbt }} owner=vagrant group=vagrant
  # - file: src=/opt/dev/scala/sbt/bin/sbt path=/usr/local/bin/sbt state=link

  - file: path={{ item }} owner=vagrant group=vagrant state=directory
    sudo: yes
    with_items:
      - /usr/lib/jvm
      - /opt/dev/java
      - /opt/dev/java/ant
      - /opt/dev/java/freemind
      - /opt/dev/scala
